name: main-pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "production"
        type: choice
        options: [development, staging, production]
      destroy:
        description: "Set to 'yes' to run terraform destroy"
        required: false
        default: "no"
        type: choice
        options: [no, yes]
      node_versions:
        description: "Comma-separated Node.js versions for unit tests"
        required: false
        default: "18,20"
      eks_cluster:
        description: "EKS cluster name for deployment"
        required: false
        default: "GP-cluster"
      aws_region:
        description: "AWS region"
        required: false
        default: "us-east-1"

  push:
    branches:
      - main

env:
  # Centralized defaults (overridable by repository/environment variables and secrets)
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}

jobs:
  unit_test:
    uses: ./.github/workflows/unit-test.yaml
    with:
      node_versions: ${{ github.event.inputs.node_versions || '18,20' }}
      os_list: ubuntu-latest
    secrets: inherit

  coverage:
    needs: unit_test
    uses: ./.github/workflows/coverage.yaml

  docker:
    needs: coverage
    uses: ./.github/workflows/docker.yaml
    permissions:
      contents: read
      packages: write
    with:
      push: true
    secrets: inherit

  terraform:
    needs: docker
    uses: ./.github/workflows/terraform.yaml
    with:
      destroy: ${{ github.event.inputs.destroy || 'no' }}
      aws_region: ${{ github.event.inputs.aws_region || 'us-east-1' }}
      environment: ${{ github.event.inputs.environment || 'production' }}
      working_directory: ./Terraform/team-01
    secrets: inherit

  deploy_helm:
    needs: terraform
    uses: ./.github/workflows/deploy.yaml
    with:
      aws_region: ${{ github.event.inputs.aws_region || 'us-east-1' }}
      eks_cluster: ${{ github.event.inputs.eks_cluster || 'GP-cluster' }}
    secrets: inherit

  observability:
    needs: deploy_helm
    uses: ./.github/workflows/observability.yaml
    with:
      aws_region: ${{ github.event.inputs.aws_region || 'us-east-1' }}
      eks_cluster: ${{ github.event.inputs.eks_cluster || 'GP-cluster' }}
    secrets: inherit

