name: terraform-deploy

on:
  workflow_call:
    inputs:
      destroy:
        description: 'Indicates if the Terraform resources should be destroyed'
        required: false
        type: string
      pipeline_input:
        description: 'Input value passed from the main pipeline'
        required: true
        type: string

jobs:
  terraform:
    name: terraform-deployment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ./Terraform/team-01

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./Terraform/team-01

      - name: Terraform Apply/Destroy
        run: |
          if [ "${{ inputs.destroy }}" = "true" ]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi
        working-directory: ./Terraform/team-01
